### ISSUE TITLE
WINDOWS problem

### ISSUE THREAD

**Issue by Ryss-D** [marcwebbie/passpie#121]
Hi guys.

i am trying to use passpie at windows, after the installation problem is done and i try to use any passpie command terminal prompt this:

Traceback (most recent call last):
  File "c:\asus\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\asus\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ASUS\Anaconda3\Scripts\passpie.exe\__main__.py", line 7, in <module>
  File "c:\asus\anaconda3\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\asus\anaconda3\lib\site-packages\click\core.py", line 695, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "c:\asus\anaconda3\lib\site-packages\click\core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "c:\asus\anaconda3\lib\site-packages\click\core.py", line 1012, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "c:\asus\anaconda3\lib\site-packages\click\core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "c:\asus\anaconda3\lib\site-packages\click\core.py", line 1397, in handle_parse_result
    value = invoke_param_callback(
  File "c:\asus\anaconda3\lib\site-packages\click\core.py", line 77, in invoke_param_callback
    return callback(ctx, param, value)
  File "c:\asus\anaconda3\lib\site-packages\passpie\validators.py", line 43, in validate_config
    configuration = config.setup_crypt(configuration)
  File "c:\asus\anaconda3\lib\site-packages\passpie\config.py", line 71, in setup_crypt
    configuration['recipient'] = get_default_recipient(configuration['homedir'])
  File "c:\asus\anaconda3\lib\site-packages\passpie\crypt.py", line 132, in get_default_recipient
    output, _ = process.call(command)
  File "c:\asus\anaconda3\lib\site-packages\passpie\process.py", line 40, in call
    with Proc(*args, **kwargs) as proc:
  File "c:\asus\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\asus\anaconda3\lib\subprocess.py", line 1247, in _execute_child
    args = list2cmdline(args)
  File "c:\asus\anaconda3\lib\subprocess.py", line 549, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "c:\asus\anaconda3\lib\os.py", line 818, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

i was trying to use it via debian on the integrate windows terminal but the clipboard doesnt work.

any idea about what can i do?

**Comment by BillCipher-exe** [comment]
same here, Passpie does not work on my Windows 11 Laptop.
installed it via PIP

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Scripts\passpie.exe\__main__.py", line 7, in <module>
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 695, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1012, in parse_args
    rest = Command.parse_args(self, ctx, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1397, in handle_parse_result
    value = invoke_param_callback(
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 77, in invoke_param_callback
    return callback(ctx, param, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\passpie\validators.py", line 43, in validate_config
    configuration = config.setup_crypt(configuration)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\passpie\config.py", line 71, in setup_crypt
    configuration['recipient'] = get_default_recipient(configuration['homedir'])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\passpie\crypt.py", line 132, in get_default_recipient
    output, _ = process.call(command)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\site-packages\passpie\process.py", line 40, in call
    with Proc(*args, **kwargs) as proc:
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1433, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Baser\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType
