### ISSUE TITLE
Package conflict

### ISSUE THREAD

**Issue by aklaver** [marcwebbie/passpie#14]
I did a pip install pysswords system  wide which succeed. Then when I tried to init a database I got the traceback below.  Repeating the install in a virtualenv an doing an init succeeded. A little digging determined that the difference was the presence of python-gnupg (https://pypi.python.org/pypi/python-gnupg/0.3.7) in the system packages.  Removing this package allowed the init to complete in the system wide install.  Thanks for program, now that I have got it running I will be using.

Traceback (most recent call last):
  File "/usr/bin/pysswords", line 9, in <module>
    load_entry_point('pysswords==0.0.12', 'console_scripts', 'pysswords')()
  File "/usr/lib/python2.7/site-packages/pysswords/__main__.py", line 85, in main
    randompass=args.random
  File "/usr/lib/python2.7/site-packages/pysswords/cli.py", line 22, in __init__
    self.create_database(path=database_path)
  File "/usr/lib/python2.7/site-packages/pysswords/cli.py", line 37, in create_database
    database = Database.create(path, passphrase)
  File "/usr/lib/python2.7/site-packages/pysswords/db/database.py", line 41, in create
    create_keyring(os.path.join(path, ".keys"), passphrase)
  File "/usr/lib/python2.7/site-packages/pysswords/crypt.py", line 27, in create_keyring
    key_input = generate_key_input(path, passphrase)
  File "/usr/lib/python2.7/site-packages/pysswords/crypt.py", line 10, in generate_key_input
    return getgpg(path).gen_key_input(
  File "/usr/lib/python2.7/site-packages/pysswords/crypt.py", line 6, in getgpg
    return gnupg.GPG(binary=which("gpg"), homedir=path)
TypeError: __init__() got an unexpected keyword argument 'binary'

**Comment by marcwebbie** [comment]
Yes, Pysswords depends on Isislovecruft fork of of [python-gnupg](https://github.com/isislovecruft/python-gnupg).

As you did, uninstall `python-gnupg` package should do the trick. Putting an error message with instructions might be a good solution. ;)

Thanks for opening the issue.
