### ISSUE TITLE
1Password import issue

### ISSUE THREAD

**Issue by gregarmer** [marcwebbie/passpie#21]
I just tried importing from 1Password `.1pif` format.

OS X Yosemite 10.10.2
1Password - Version 5.1 (510027) - Mac App Store

Here's the traceback:

```pytb
Traceback (most recent call last):
  File "/Users/greg/.virtualenvs/pysswords/bin/pysswords", line 9, in <module>
    load_entry_point('pysswords==0.0.12', 'console_scripts', 'pysswords')()
  File "/Users/greg/.virtualenvs/pysswords/lib/python2.7/site-packages/pysswords/__main__.py", line 91, in main
    interface.importdb(args.importdb)
  File "/Users/greg/.virtualenvs/pysswords/lib/python2.7/site-packages/pysswords/cli.py", line 184, in importdb
    self.database.importdb(dbfile)
  File "/Users/greg/.virtualenvs/pysswords/lib/python2.7/site-packages/pysswords/db/database.py", line 148, in importdb
    self.import1password(dbfile)
  File "/Users/greg/.virtualenvs/pysswords/lib/python2.7/site-packages/pysswords/db/database.py", line 154, in import1password
    creds = parsers.onepassword(dbfile)
  File "/Users/greg/.virtualenvs/pysswords/lib/python2.7/site-packages/pysswords/db/parsers.py", line 15, in onepassword
    "password": entry["secureContents"]["password"],
KeyError: 'password'
```

The format of the record is:

```
{u'contentsHash': u'8b293941',
 u'createdAt': 1413128818,
 u'location': u'https://support.ford.com/tools/account/login',
 u'locationKey': u'ford.com',
 u'secureContents': {u'URLs': [{u'label': u'website',
                                u'url': u'https://support.ford.com/tools/account/login'}],
                     u'fields': [{u'designation': u'username',
                                  u'name': u'username',
                                  u'type': u'T',
                                  u'value': u'greg@example.com'},
                                 {u'designation': u'password',
                                  u'name': u'password',
                                  u'type': u'P',
                                  u'value': u'my-redacted-password'}]},
 u'securityLevel': u'SL5',
 u'title': u'MyFord',
 u'typeName': u'webforms.WebForm',
 u'updatedAt': 1413128834,
 u'uuid': u'98C1AB23A1FF4EBAB5342189B0C8B861'}
```

Relevant code from the parser:

```python
for entry in entries:
    print entry
    cred_dict = {
        "name": entry["title"],
        "login": "",
        "password": entry["secureContents"]["password"],
        "comment": entry["secureContents"].get("notesPlain", "")
    }
```

I'm not sure if this is a newer version of the export format, but the parser doesn't match the record format very well; `password` isn't correct, `login` is set to an empty string and `comment` isn't set at all.

**Comment by marcwebbie** [comment]
Hey @gregarmer 

I am now working on importers, I will investigate more on those parsing errors, it seems that 1password generates a different format of 1pif on my mac and I also have version 5.1.

Thanks for opening this issue. ;)

**Comment by marcwebbie** [comment]
Hello @gregarmer 

I will be closing this issue since csv importers are now implemented. Feel free to reopen if you experience any issues.

Thanks for your contribution

Exporting 1password credentials as CSV:
https://discussions.agilebits.com/discussion/10992/export-1password-data-as-csv-file

Importing CSV to passpie:
http://passpie.readthedocs.org/en/latest/getting_started.html#importing-credentials

**Comment by gregarmer** [comment]
Awesome thanks @marcwebbie :+1: 

Thanks for a great tool!
