### ISSUE TITLE
TypeError: must be encoded string without NULL bytes, not str

### ISSUE THREAD

**Issue by fobdy** [marcwebbie/passpie#24]
Python 2.7.3
Mac OS X 10.8.5 (Mountain Lion)
Installed with easy_install.

```bash
~ ↝ pysswords
Traceback (most recent call last):
  File "/usr/local/bin/pysswords", line 8, in <module>
    load_entry_point('pysswords==0.0.12', 'console_scripts', 'pysswords')()
  File "/Library/Python/2.7/site-packages/pysswords-0.0.12-py2.7.egg/pysswords/__main__.py", line 85, in main
    randompass=args.random
  File "/Library/Python/2.7/site-packages/pysswords-0.0.12-py2.7.egg/pysswords/cli.py", line 23, in __init__
    self.database = Database(database_path)
  File "/Library/Python/2.7/site-packages/pysswords-0.0.12-py2.7.egg/pysswords/db/database.py", line 33, in __init__
    self.gpg = getgpg(self.keys_path)
  File "/Library/Python/2.7/site-packages/pysswords-0.0.12-py2.7.egg/pysswords/crypt.py", line 6, in getgpg
    return gnupg.GPG(binary=which("gpg"), homedir=path)
  File "/Library/Python/2.7/site-packages/gnupg-1.4.0-py2.7.egg/gnupg/gnupg.py", line 120, in __init__
    use_agent=use_agent,)
  File "/Library/Python/2.7/site-packages/gnupg-1.4.0-py2.7.egg/gnupg/_meta.py", line 214, in __init__
    self._check_sane_and_get_gpg_version()
  File "/Library/Python/2.7/site-packages/gnupg-1.4.0-py2.7.egg/gnupg/_meta.py", line 475, in _check_sane_and_get_gpg_version
    proc = self._open_subprocess(["--list-config", "--with-colons"])
  File "/Library/Python/2.7/site-packages/gnupg-1.4.0-py2.7.egg/gnupg/_meta.py", line 577, in _open_subprocess
    env={'LANGUAGE': 'en'})
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1228, in _execute_child
    raise child_exception
TypeError: must be encoded string without NULL bytes, not str
```

**Comment by fobdy** [comment]
P.S. gnupg output is not in english

**Comment by marcwebbie** [comment]
Hello @fobdy , 

What version of pysswords you have installed? I also work on Mac OS and my system is not in English as well.

+ Have you ever run pysswords with success before? 
+ If so, did you run `pysswords --init`?
+ Do you have any version of Python3 installed? if so try testing with that:

```
virtualenv -p `which python3` py3env
source py3env/bin/activate
pip install pysswords
pysswords --init
pysswords
```

Thanks

**Comment by marcwebbie** [comment]
Closing for the moment, 

Pysswords development has been moved to Passpie.
