### ISSUE TITLE
Pyperclip requires the xclip or xsel application, or the gtk or PyQt4 module

### ISSUE THREAD

**Issue by alissonperez** [marcwebbie/passpie#42]
I installed passpie in my Ubuntu 14.04 but I received the error below when I tried to execute it:

    Traceback (most recent call last):
      File "/usr/local/bin/passpie", line 7, in <module>
        from passpie.cli import cli
      File "/usr/local/lib/python3.4/dist-packages/passpie/cli.py", line 9, in <module>
        import pyperclip
      File "/usr/local/lib/python3.4/dist-packages/pyperclip/__init__.py", line 203, in <module>
        raise Exception('Pyperclip requires the xclip or xsel application, or the gtk or PyQt4 module.')
    Exception: Pyperclip requires the xclip or xsel application, or the gtk or PyQt4 module.

Tell me if you need more information about my environment.

[]'s

**Comment by marcwebbie** [comment]
Yes, you should install xclip if you are on Ubuntu. I will have to add this information on the README.

Thanks for opening up the issue.
