### ISSUE TITLE
Crash when copying passwords

### ISSUE THREAD

**Issue by bascht** [marcwebbie/passpie#49]
```bash
$ passpie copy bascht@company/example.com
Passphrase: 
Traceback (most recent call last):
  File "/home/bascht/.local/bin/passpie", line 11, in <module>
    sys.exit(cli())
  File "/home/bascht/.local/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/home/bascht/.local/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/home/bascht/.local/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bascht/.local/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bascht/.local/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/home/bascht/.local/lib/python2.7/site-packages/passpie/cli.py", line 275, in copy
    copy_to_clipboard(decrypted)
  File "/home/bascht/.local/lib/python2.7/site-packages/passpie/cli.py", line 110, in copy_to_clipboard
    clipboard.copy(text)
  File "/home/bascht/.local/lib/python2.7/site-packages/passpie/clipboard.py", line 83, in copy
    _copy_linux(text)
  File "/home/bascht/.local/lib/python2.7/site-packages/passpie/clipboard.py", line 75, in _copy_linux
    p = Popen(command, stdin=PIPE, close_fds=True)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1214, in _execute_child
    executable = args[0]
IndexError: list index out of range
```

## System

```bash
$ passpie --version
passpie, version 0.2.1

$ python --version
Python 2.7.9

$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 22 (Twenty Two)
Release:	22
Codename:	TwentyTwo
```

Let me know if I can supply more information! :)

**Comment by marcwebbie** [comment]
Hello @bascht,

how did you install passpie? Do you have `xclip` or `xsel` installed? Tell me output of those commands:

```
which passpie
```

```
which xclip
```

```
which xsel
```

Thanks for reporting.

**Comment by bascht** [comment]
```bash
$ which passpie
/home/bascht/.local/bin/passpie

$ which xclip
/usr/bin/xclip

$ xclip -version
xclip version 0.12

$ which xsel
/usr/bin/xsel

$ xsel --version
xsel version 1.2.0 by Conrad Parker <conrad@vergenet.net>
```

When checking the actual values in `clipboard.py`, the `LINUX_COMMANDS` dict is empty as in #44, it looks like I got a faulty version by running `pip install --user --upgrade passpie`. :)

**Comment by bascht** [comment]
Just checked with PyPi. The tag v0.2.1 is probably broken for linux users. ;)

**Comment by marcwebbie** [comment]
Oh thanks for the info,

I am bumping version with those last patches. :)

**Comment by bascht** [comment]
Thanks for the bump! Sorry to bother you again, but it looks like I ran into the next issue here:

```bash
> passpie copy bascht@company/example.com
Passphrase: 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/bascht/.local/lib/python2.7/site-packages/gnupg/_meta.py", line 626, in _read_response
    result._handle_status(keyword, value)
  File "/home/bascht/.local/lib/python2.7/site-packages/gnupg/_parsers.py", line 1137, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'PINENTRY_LAUNCHED'
```

Should I a new issue? :-)
