### ISSUE TITLE
Pysswords import

### ISSUE THREAD

**Issue by mattiacorvaglia** [marcwebbie/passpie#73]
I tried to import a database exported with Pysswords using the command
`passpie import dbname.db`
but I get this error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/passpie/0.3.2/libexec/bin/passpie", line 9, in <module>
    load_entry_point('passpie==0.3.2', 'console_scripts', 'passpie')()
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/passpie/0.3.2/libexec/lib/python2.7/site-packages/passpie/cli.py", line 410, in import_database
    importer = find_importer(path)
  File "/usr/local/Cellar/passpie/0.3.2/libexec/lib/python2.7/site-packages/passpie/importers/__init__.py", line 51, in find_importer
    if importer.match(filepath):
  File "/usr/local/Cellar/passpie/0.3.2/libexec/lib/python2.7/site-packages/passpie/importers/default_importer.py", line 17, in match
    dict_content = yaml.load(file_content)
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/yaml/reader.py", line 79, in __init__
    self.determine_encoding()
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/usr/local/Cellar/passpie/0.3.2/libexec/vendor/lib/python2.7/site-packages/yaml/reader.py", line 165, in update
    exc.encoding, exc.reason)
yaml.reader.ReaderError: 'utf8' codec can't decode byte #x99: invalid start byte
  in "<string>", position 1536
```
I installed Passpie using Homebrew on Mac OS X 10.10.5

**Comment by marcwebbie** [comment]
What is the version of Pysswords you had when exporting the database?

Did you update pysswords before?

```
pip install -U pysswords
```

Thanks for opening this issue

**Comment by mattiacorvaglia** [comment]
No, actually I have not updated it before, the version is the 0.0.12

**Comment by marcwebbie** [comment]
Could you try updating `Pysswords` and re running again?

Thanks

**Comment by marcwebbie** [comment]
Since it has happened no activity on this issue. I will be closing this issue for now.
